# Generated by Django 2.2.14 on 2021-09-01 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideapeacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_idea', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 9, 1, 15, 3, 53, 689644))),
                ('pdf', models.FileField(blank=True, upload_to='book/pdfs')),
                ('category', models.ManyToManyField(to='ideapeacher.category')),
                ('peacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ideapeacher.ideapeacher')),
            ],
        ),
    ]
