# Generated by Django 2.2.14 on 2021-09-02 10:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideapeacher', '0002_category_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 2, 15, 49, 21, 664617)),
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 9, 2, 15, 49, 21, 667158))),
                ('by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ideapeacher.idea')),
            ],
        ),
    ]
